### ISSUE TITLE
Pulling in Auro Components in React/TS + Jest

### ISSUE THREAD

**Issue by rallyb13** [AlaskaAirlines/auro-button#110] opened 2021-05-07 22:11 UTC
## Support request
Setting up Auro for LoungeMembership-Web, I was able to pull components in fine for the application, but Jest testing threw an error: "Cannot use import statement outside a module"

## Possible Solution
While there are ways to reconfigure jest to handle this, I'm weary of making changes that might force us to eject from `create-react-app` standard configuration. This may be the territory we have to wade deeper into.
So instead of walking in blind there, we chose to attempt to use the bundled version of components instead, hoping that pulling the components in differently would avoid the error, and it did. [see branch](https://dev.azure.com/itsals/E_Retain_NonFlightPartners/_git/LoungeMembership-Web?version=GBhotfix-auro-jest)
Unfortunately, it also ripped all the styles off the components (as well as the ability to configure the components).

## Context
Just trying to find the best way to pull in Auro components && get past the Jest aversion to exterior modules.

## Your Environment
* Version used: of Auro? Just pulled in yesterday following the setup instructions. Node: 14.16.1 NPM: 7.11.1
* Browser Name and version: Chrome 90.0.4430.93 (but probably N/A
* Operating System and version (desktop or mobile): Macbook Pro
* Link to your project: 
https://dev.azure.com/itsals/E_Retain_NonFlightPartners/_git/LoungeMembership-Web

**Comment by blackfalcon** [comment] 2021-05-07 23:08
Transferred issue to auro-button as this is more custom element related versus stylesheet related. Also, this is not a bug with auro-button, as the issue being had would happen with any auro custom element. 

@geoffrich is on the case! 

A follow up to this issue could be to add additional support to this page https://auro.alaskaair.com/support/tests

**Comment by blackfalcon** [comment] 2021-05-07 23:12
@rallyb13 note that your version of design tokens in your project is out of date

```
"@alaskaairux/orion-web-core-style-sheets": "^2.12.2",
```

That version has been fully deprecated. See the [install](https://github.com/AlaskaAirlines/AuroDesignTokens#install)

**Comment by geoffrich** [comment] 2021-05-07 23:26
I created a [test repo](https://github.com/geoffrich/react-auro-jest) with Create React App and auro-button and got the tests to pass. It doesn't use TypeScript, but I don't think that's a factor in the error you're seeing. Try making the following changes:

- Update your test script in package.json to pass [transformIgnorePatterns](https://jestjs.io/docs/configuration#transformignorepatterns-arraystring). This will instruct Jest to transpile the Auro packages and related dependencies. Luckily, this doesn't require ejecting from CRA.
```
"test": "react-scripts test --transformIgnorePatterns \"/node_modules/(?!@alaskaairux|lit-element|lit-html|lit)\"",
```
- In each test file, un-set window.applyFocusVisiblePolyfill. This was causing JSDOM to throw an "NotSupportedError: Unexpected attributes" error that I need to investigate further. I'm hoping there's a better way around this, but for now, this will make the tests pass.
```js
beforeAll(() => {
  window.applyFocusVisiblePolyfill = null;
});
```

I'm going to dig in a bit more and create documentation for what I find before closing this issue.

**Comment by geoffrich** [comment] 2021-05-10 15:35
Also, for future reference: avoid importing the bundled versions of Auro components. They are intended for use in environments that don't have a bundling setup. Importing multiple bundled components will increase bundle size unnecessarily, since you'll include multiple copies of Auro dependencies.

**Comment by blackfalcon** [comment] 2021-05-10 16:15
> Also, for future reference: avoid importing the bundled versions of Auro components. 

Yes, for projects that have JS bundle processes, e.g. React, users shouldn't be using pre-bundled CDN assets. The primary install is to install the npm package as a dependency. 

CDN bundled assets are intended for projects that do not have a JS pipeline and/or are static HTML documents, e.g. markdown.

**Comment by jason-capsule42** [comment] 2021-05-10 20:51
After having a followup call with @rallyb13 on the call I am closing this issue.

https://github.com/AlaskaAirlines/AuroDocsSite/issues/35 created as a followup ticket to update documentation that was out of date.

**Closed by jason-capsule42** 2021-05-10 20:51 UTC
Labels: Status: Work In Progress, Type: Testing

**Comment by blackfalcon** [comment] 2021-05-10 21:28
Great user support on this one @jason-capsule42 and @geoffrich. Thanks for all your help with this. 

Thanks for writing up https://github.com/AlaskaAirlines/AuroDocsSite/issues/35 @jason-capsule42 

@geoffrich as a follow-up to this issue, what are your thoughts about documenting this I created https://github.com/AlaskaAirlines/AuroReactDemo/issues/16

**Comment by geoffrich** [comment] 2021-05-10 23:28
Turns out the `window.applyFocusVisiblePolyfill` workaround was an actual bug in the component. See #112. Once this is fixed, you shouldn't need to add that code to your tests.
